/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkflowsIndexRouteImport } from './routes/workflows/index'
import { Route as TracesIndexRouteImport } from './routes/traces/index'
import { Route as TasksIndexRouteImport } from './routes/tasks/index'
import { Route as SkillsIndexRouteImport } from './routes/skills/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as ProjectsIndexRouteImport } from './routes/projects/index'
import { Route as PlansIndexRouteImport } from './routes/plans/index'
import { Route as OverviewIndexRouteImport } from './routes/overview/index'
import { Route as MetricsIndexRouteImport } from './routes/metrics/index'
import { Route as MemoryIndexRouteImport } from './routes/memory/index'
import { Route as InboxIndexRouteImport } from './routes/inbox/index'
import { Route as HealthIndexRouteImport } from './routes/health/index'
import { Route as GoalsIndexRouteImport } from './routes/goals/index'
import { Route as CostsIndexRouteImport } from './routes/costs/index'
import { Route as ChatIndexRouteImport } from './routes/chat/index'
import { Route as AgentsIndexRouteImport } from './routes/agents/index'
import { Route as TracesTraceIdRouteImport } from './routes/traces/$traceId'
import { Route as TasksTaskIdRouteImport } from './routes/tasks/$taskId'
import { Route as SkillsSkillNameRouteImport } from './routes/skills/$skillName'
import { Route as ProjectsNewRouteImport } from './routes/projects/new'
import { Route as ProjectsProjectIdRouteImport } from './routes/projects/$projectId'
import { Route as PlansPlanIdRouteImport } from './routes/plans/$planId'
import { Route as AgentsAgentIdRouteImport } from './routes/agents/$agentId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkflowsIndexRoute = WorkflowsIndexRouteImport.update({
  id: '/workflows/',
  path: '/workflows/',
  getParentRoute: () => rootRouteImport,
} as any)
const TracesIndexRoute = TracesIndexRouteImport.update({
  id: '/traces/',
  path: '/traces/',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksIndexRoute = TasksIndexRouteImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillsIndexRoute = SkillsIndexRouteImport.update({
  id: '/skills/',
  path: '/skills/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlansIndexRoute = PlansIndexRouteImport.update({
  id: '/plans/',
  path: '/plans/',
  getParentRoute: () => rootRouteImport,
} as any)
const OverviewIndexRoute = OverviewIndexRouteImport.update({
  id: '/overview/',
  path: '/overview/',
  getParentRoute: () => rootRouteImport,
} as any)
const MetricsIndexRoute = MetricsIndexRouteImport.update({
  id: '/metrics/',
  path: '/metrics/',
  getParentRoute: () => rootRouteImport,
} as any)
const MemoryIndexRoute = MemoryIndexRouteImport.update({
  id: '/memory/',
  path: '/memory/',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxIndexRoute = InboxIndexRouteImport.update({
  id: '/inbox/',
  path: '/inbox/',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthIndexRoute = HealthIndexRouteImport.update({
  id: '/health/',
  path: '/health/',
  getParentRoute: () => rootRouteImport,
} as any)
const GoalsIndexRoute = GoalsIndexRouteImport.update({
  id: '/goals/',
  path: '/goals/',
  getParentRoute: () => rootRouteImport,
} as any)
const CostsIndexRoute = CostsIndexRouteImport.update({
  id: '/costs/',
  path: '/costs/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatIndexRoute = ChatIndexRouteImport.update({
  id: '/chat/',
  path: '/chat/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsIndexRoute = AgentsIndexRouteImport.update({
  id: '/agents/',
  path: '/agents/',
  getParentRoute: () => rootRouteImport,
} as any)
const TracesTraceIdRoute = TracesTraceIdRouteImport.update({
  id: '/traces/$traceId',
  path: '/traces/$traceId',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksTaskIdRoute = TasksTaskIdRouteImport.update({
  id: '/tasks/$taskId',
  path: '/tasks/$taskId',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillsSkillNameRoute = SkillsSkillNameRouteImport.update({
  id: '/skills/$skillName',
  path: '/skills/$skillName',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsNewRoute = ProjectsNewRouteImport.update({
  id: '/projects/new',
  path: '/projects/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIdRoute = ProjectsProjectIdRouteImport.update({
  id: '/projects/$projectId',
  path: '/projects/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const PlansPlanIdRoute = PlansPlanIdRouteImport.update({
  id: '/plans/$planId',
  path: '/plans/$planId',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsAgentIdRoute = AgentsAgentIdRouteImport.update({
  id: '/agents/$agentId',
  path: '/agents/$agentId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agents/$agentId': typeof AgentsAgentIdRoute
  '/plans/$planId': typeof PlansPlanIdRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/projects/new': typeof ProjectsNewRoute
  '/skills/$skillName': typeof SkillsSkillNameRoute
  '/tasks/$taskId': typeof TasksTaskIdRoute
  '/traces/$traceId': typeof TracesTraceIdRoute
  '/agents/': typeof AgentsIndexRoute
  '/chat/': typeof ChatIndexRoute
  '/costs/': typeof CostsIndexRoute
  '/goals/': typeof GoalsIndexRoute
  '/health/': typeof HealthIndexRoute
  '/inbox/': typeof InboxIndexRoute
  '/memory/': typeof MemoryIndexRoute
  '/metrics/': typeof MetricsIndexRoute
  '/overview/': typeof OverviewIndexRoute
  '/plans/': typeof PlansIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/skills/': typeof SkillsIndexRoute
  '/tasks/': typeof TasksIndexRoute
  '/traces/': typeof TracesIndexRoute
  '/workflows/': typeof WorkflowsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agents/$agentId': typeof AgentsAgentIdRoute
  '/plans/$planId': typeof PlansPlanIdRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/projects/new': typeof ProjectsNewRoute
  '/skills/$skillName': typeof SkillsSkillNameRoute
  '/tasks/$taskId': typeof TasksTaskIdRoute
  '/traces/$traceId': typeof TracesTraceIdRoute
  '/agents': typeof AgentsIndexRoute
  '/chat': typeof ChatIndexRoute
  '/costs': typeof CostsIndexRoute
  '/goals': typeof GoalsIndexRoute
  '/health': typeof HealthIndexRoute
  '/inbox': typeof InboxIndexRoute
  '/memory': typeof MemoryIndexRoute
  '/metrics': typeof MetricsIndexRoute
  '/overview': typeof OverviewIndexRoute
  '/plans': typeof PlansIndexRoute
  '/projects': typeof ProjectsIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/skills': typeof SkillsIndexRoute
  '/tasks': typeof TasksIndexRoute
  '/traces': typeof TracesIndexRoute
  '/workflows': typeof WorkflowsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agents/$agentId': typeof AgentsAgentIdRoute
  '/plans/$planId': typeof PlansPlanIdRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/projects/new': typeof ProjectsNewRoute
  '/skills/$skillName': typeof SkillsSkillNameRoute
  '/tasks/$taskId': typeof TasksTaskIdRoute
  '/traces/$traceId': typeof TracesTraceIdRoute
  '/agents/': typeof AgentsIndexRoute
  '/chat/': typeof ChatIndexRoute
  '/costs/': typeof CostsIndexRoute
  '/goals/': typeof GoalsIndexRoute
  '/health/': typeof HealthIndexRoute
  '/inbox/': typeof InboxIndexRoute
  '/memory/': typeof MemoryIndexRoute
  '/metrics/': typeof MetricsIndexRoute
  '/overview/': typeof OverviewIndexRoute
  '/plans/': typeof PlansIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/skills/': typeof SkillsIndexRoute
  '/tasks/': typeof TasksIndexRoute
  '/traces/': typeof TracesIndexRoute
  '/workflows/': typeof WorkflowsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agents/$agentId'
    | '/plans/$planId'
    | '/projects/$projectId'
    | '/projects/new'
    | '/skills/$skillName'
    | '/tasks/$taskId'
    | '/traces/$traceId'
    | '/agents/'
    | '/chat/'
    | '/costs/'
    | '/goals/'
    | '/health/'
    | '/inbox/'
    | '/memory/'
    | '/metrics/'
    | '/overview/'
    | '/plans/'
    | '/projects/'
    | '/settings/'
    | '/skills/'
    | '/tasks/'
    | '/traces/'
    | '/workflows/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agents/$agentId'
    | '/plans/$planId'
    | '/projects/$projectId'
    | '/projects/new'
    | '/skills/$skillName'
    | '/tasks/$taskId'
    | '/traces/$traceId'
    | '/agents'
    | '/chat'
    | '/costs'
    | '/goals'
    | '/health'
    | '/inbox'
    | '/memory'
    | '/metrics'
    | '/overview'
    | '/plans'
    | '/projects'
    | '/settings'
    | '/skills'
    | '/tasks'
    | '/traces'
    | '/workflows'
  id:
    | '__root__'
    | '/'
    | '/agents/$agentId'
    | '/plans/$planId'
    | '/projects/$projectId'
    | '/projects/new'
    | '/skills/$skillName'
    | '/tasks/$taskId'
    | '/traces/$traceId'
    | '/agents/'
    | '/chat/'
    | '/costs/'
    | '/goals/'
    | '/health/'
    | '/inbox/'
    | '/memory/'
    | '/metrics/'
    | '/overview/'
    | '/plans/'
    | '/projects/'
    | '/settings/'
    | '/skills/'
    | '/tasks/'
    | '/traces/'
    | '/workflows/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgentsAgentIdRoute: typeof AgentsAgentIdRoute
  PlansPlanIdRoute: typeof PlansPlanIdRoute
  ProjectsProjectIdRoute: typeof ProjectsProjectIdRoute
  ProjectsNewRoute: typeof ProjectsNewRoute
  SkillsSkillNameRoute: typeof SkillsSkillNameRoute
  TasksTaskIdRoute: typeof TasksTaskIdRoute
  TracesTraceIdRoute: typeof TracesTraceIdRoute
  AgentsIndexRoute: typeof AgentsIndexRoute
  ChatIndexRoute: typeof ChatIndexRoute
  CostsIndexRoute: typeof CostsIndexRoute
  GoalsIndexRoute: typeof GoalsIndexRoute
  HealthIndexRoute: typeof HealthIndexRoute
  InboxIndexRoute: typeof InboxIndexRoute
  MemoryIndexRoute: typeof MemoryIndexRoute
  MetricsIndexRoute: typeof MetricsIndexRoute
  OverviewIndexRoute: typeof OverviewIndexRoute
  PlansIndexRoute: typeof PlansIndexRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
  SkillsIndexRoute: typeof SkillsIndexRoute
  TasksIndexRoute: typeof TasksIndexRoute
  TracesIndexRoute: typeof TracesIndexRoute
  WorkflowsIndexRoute: typeof WorkflowsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflows/': {
      id: '/workflows/'
      path: '/workflows'
      fullPath: '/workflows/'
      preLoaderRoute: typeof WorkflowsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/traces/': {
      id: '/traces/'
      path: '/traces'
      fullPath: '/traces/'
      preLoaderRoute: typeof TracesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/': {
      id: '/tasks/'
      path: '/tasks'
      fullPath: '/tasks/'
      preLoaderRoute: typeof TasksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skills/': {
      id: '/skills/'
      path: '/skills'
      fullPath: '/skills/'
      preLoaderRoute: typeof SkillsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plans/': {
      id: '/plans/'
      path: '/plans'
      fullPath: '/plans/'
      preLoaderRoute: typeof PlansIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/overview/': {
      id: '/overview/'
      path: '/overview'
      fullPath: '/overview/'
      preLoaderRoute: typeof OverviewIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metrics/': {
      id: '/metrics/'
      path: '/metrics'
      fullPath: '/metrics/'
      preLoaderRoute: typeof MetricsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memory/': {
      id: '/memory/'
      path: '/memory'
      fullPath: '/memory/'
      preLoaderRoute: typeof MemoryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox/': {
      id: '/inbox/'
      path: '/inbox'
      fullPath: '/inbox/'
      preLoaderRoute: typeof InboxIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health/': {
      id: '/health/'
      path: '/health'
      fullPath: '/health/'
      preLoaderRoute: typeof HealthIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/goals/': {
      id: '/goals/'
      path: '/goals'
      fullPath: '/goals/'
      preLoaderRoute: typeof GoalsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/costs/': {
      id: '/costs/'
      path: '/costs'
      fullPath: '/costs/'
      preLoaderRoute: typeof CostsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/': {
      id: '/chat/'
      path: '/chat'
      fullPath: '/chat/'
      preLoaderRoute: typeof ChatIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/': {
      id: '/agents/'
      path: '/agents'
      fullPath: '/agents/'
      preLoaderRoute: typeof AgentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/traces/$traceId': {
      id: '/traces/$traceId'
      path: '/traces/$traceId'
      fullPath: '/traces/$traceId'
      preLoaderRoute: typeof TracesTraceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/$taskId': {
      id: '/tasks/$taskId'
      path: '/tasks/$taskId'
      fullPath: '/tasks/$taskId'
      preLoaderRoute: typeof TasksTaskIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skills/$skillName': {
      id: '/skills/$skillName'
      path: '/skills/$skillName'
      fullPath: '/skills/$skillName'
      preLoaderRoute: typeof SkillsSkillNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/new': {
      id: '/projects/new'
      path: '/projects/new'
      fullPath: '/projects/new'
      preLoaderRoute: typeof ProjectsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId': {
      id: '/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof ProjectsProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plans/$planId': {
      id: '/plans/$planId'
      path: '/plans/$planId'
      fullPath: '/plans/$planId'
      preLoaderRoute: typeof PlansPlanIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/$agentId': {
      id: '/agents/$agentId'
      path: '/agents/$agentId'
      fullPath: '/agents/$agentId'
      preLoaderRoute: typeof AgentsAgentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgentsAgentIdRoute: AgentsAgentIdRoute,
  PlansPlanIdRoute: PlansPlanIdRoute,
  ProjectsProjectIdRoute: ProjectsProjectIdRoute,
  ProjectsNewRoute: ProjectsNewRoute,
  SkillsSkillNameRoute: SkillsSkillNameRoute,
  TasksTaskIdRoute: TasksTaskIdRoute,
  TracesTraceIdRoute: TracesTraceIdRoute,
  AgentsIndexRoute: AgentsIndexRoute,
  ChatIndexRoute: ChatIndexRoute,
  CostsIndexRoute: CostsIndexRoute,
  GoalsIndexRoute: GoalsIndexRoute,
  HealthIndexRoute: HealthIndexRoute,
  InboxIndexRoute: InboxIndexRoute,
  MemoryIndexRoute: MemoryIndexRoute,
  MetricsIndexRoute: MetricsIndexRoute,
  OverviewIndexRoute: OverviewIndexRoute,
  PlansIndexRoute: PlansIndexRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
  SettingsIndexRoute: SettingsIndexRoute,
  SkillsIndexRoute: SkillsIndexRoute,
  TasksIndexRoute: TasksIndexRoute,
  TracesIndexRoute: TracesIndexRoute,
  WorkflowsIndexRoute: WorkflowsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
